### ISSUE TITLE
v-000 version is not inline with the canocical

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/angular-automated-transclusion-lab#2]
This lab (canonical) has a package.json file, which is missing in the v-000 lab. Somehow the update was not merged into v-000. Students already opened an issue on batch level.

https://github.com/learn-co-students/angular-automated-transclusion-lab-v-000/issues/17

@Lukeghenco @AnnJohn @aturkewi

**Comment by aturkewi** [comment]
Re-deployed the lab. Fixed: https://github.com/learn-co-students/angular-automated-transclusion-lab-v-000
